### ISSUE TITLE
Branch isn't logging my events

### ISSUE THREAD

**Issue by erikjthomas** [distriqt/ANE-BranchIO#10]
I carefully followed the Wiki instructions, and init is successful, and all my event calls are showing success, but nothing is getting logged on Branch.

I have sent a support request to branch.io as instructed. Haven't heard back yet, but I expect I'm just not doing some little thing.

Was wondering if we could buy some of your time to help us get this working? Branch doesn't have any live support and we can't figure out how to troubleshoot this issue. There are no troubleshooting tools we can find to figure this out and we're sick of reading docs on the branch.io site and not finding any answers. 

It might be as simple as setting up a journey or something else that's undocumented for this ANE.

BTW, we'd rather pay for ANEs and get support than use free ones but had no choice on this one. Again, glad to pay your going rate to help us figure this out.

Thanks.

Erik
Linqto, Inc.

**Comment by marchbold** [comment]
Hi Erik,

Email us at airnativeextensions@distriqt.com. This ANE definitely needs some attention and we haven't looked at it in a while.
