### ISSUE TITLE
Track iOS subscription event for app downloaded from Apple Search Ads

### ISSUE THREAD

**Issue by idzdigital** [distriqt/ANE-BranchIO#12]
Hi,
I have an iOS application with auto renewable subscription. Can I use this ANE to log subscription purchase event for users who have installed the application via Apple Search Ads?
Thanks!

**Comment by marchbold** [comment]
You can use the event tracking to track purchases but I'm not sure how that relates to Apple Search Ads.

https://github.com/distriqt/ANE-BranchIO/wiki/u.Event-Tracking

**Comment by idzdigital** [comment]
ok will see if we can link that data to Apple Search Ads
