### ISSUE TITLE
Android events

### ISSUE THREAD

**Issue by ilyaround** [distriqt/ANE-BranchIO#4]
Hello. 

Due to some unknown reason we cannot see all info for Android, though for iOS everything works well. In the end all events except Revenue and Transaction id loaded http://take.ms/ClsMw

It’s weard because settings for iOS and Android are the same.

Could you help us solve this problem as well?

Thank you

**Comment by marchbold** [comment]
Could you show us the code you are using?

**Comment by ilyaround** [comment]
> Could you show us the code you are using?

Xml-manifest https://cloud.bstd.ru/s/brXZXWcjSvknFbm
Code https://cloud.bstd.ru/s/gXejpqnXdgRvFw9
The finished application file https://cloud.bstd.ru/s/a2Ogg7AEiaWwcef

The test App is very simple. We created the test app for testing Branch ANE. There are 2 buttons with events to branch and log. 

Thank you.

**Comment by marchbold** [comment]
Can't see anything wrong with the code and haven't had any time to investigate further. Could you post the logs from the device at all?

https://airnativeextensions.github.io/tutorials/device-logs
