### ISSUE TITLE
URI scheme - not getting link parameter

### ISSUE THREAD

**Issue by idanasher** [distriqt/ANE-BranchIO#6]
I have recently started using this ane.
started my integration with my android app, 64Bit AIR 33 (latest).

I use this link:
https://rummy-world.app.link/?followMe=10295431

The 'followMe' parameter  is working good and I get it on the init branch event after I call
Branch.instance.initSession.
When clicking the link, its opening the google play application page and then OPEN will open the app with the right parameter, as expected.

But, when I add following to the manifest - the application is opening directly (no google play in between) but the parameter is not getting in the branch init. I get no extra parameters at all.

		
		<activity android:launchMode="singleTask">
			<intent-filter>
				<action android:name="android.intent.action.MAIN"/>
				<category android:name="android.intent.category.LAUNCHER"/>
			</intent-filter>

			
			<intent-filter>
				<data android:scheme="rummyworld" android:host="open" />
				<action android:name="android.intent.action.VIEW" />
				<category android:name="android.intent.category.DEFAULT" />
				<category android:name="android.intent.category.BROWSABLE" />
			</intent-filter>
			 
			
            
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="https" android:host="rummy-world.app.link" />                
            </intent-filter>
			
		</activity>		

I have tried everything, including every option on the branch console...
How can I get this to work directly ?

Cheers and thanks

**Comment by marchbold** [comment]
Can you post the device logs when opening the link? Sometimes there's some useful information in there.

https://airnativeextensions.github.io/tutorials/device-logs
