### ISSUE TITLE
New  Play Install Referrer API 

### ISSUE THREAD

**Issue by idanasher** [distriqt/ANE-BranchIO#8]
I have recently received this email from branch , regarding the removal of **install_referrer** and instructions regrading the new googple api:
http://go2.branch.io/HF001080YlXgpTv0BqT00Aj

**Are we ready for this ?**
It is real soon...

This is the email from branch:	
Hi Edan,

A couple of months ago, Google announced that they will stop broadcasting install_referrer intents on March 1, 2020. Branch uses this data to help power our deep linking and attribution services on Android devices.

Fortunately, Google has also introduced the Play Install Referrer API to provide the same data. This API provides better performance, and there is a good chance it is already configured in your app. However, Google has recently contacted several Branch customers about this, so we wanted to proactively reach out and help you confirm your configuration in advance of the cutoff date.

**REQUIRED ACTIONS**

Branch Android SDK: please do EITHER of the following for your Android app:

1. Ensure you've linked the Play Install Referrer Library as a Gradle dependency. To do this, please add this directive to your build.gradle file (it is not necessary to implement any of the other steps on this page, as the Branch SDK will handle the rest for you). 

OR

2. Update to the most recent version of the SDK (v4.3.2), which bundles the Play Install Referrer Library automatically.

TUNE Android SDK: Please update to the most recent version of the SDK (v6.1.2, currently only available on JCenter). The TUNE Android SDK already bundles the Play Install Referrer Library, but older versions contain a rare bug that can cause a background thread to pause for up to 60 seconds while waiting for install_referrer data to be returned.

In addition, we recommend confirming that the following entry has been removed from your AndroidManifest.xml file:

Branch SDK

<receiver android:name="io.branch.referral.InstallListener" android:exported="true">
   <intent-filter>
   <action android:name="com.android.vending.INSTALL_REFERRER" />
   </intent-filter>
</receiver>

TUNE SDK

<receiver android:name="com.tune.TuneTracker">
    <intent-filter>
    <action android:name="com.android.vending.INSTALL_REFERRER" />
    </intent-filter>
</receiver>

If you have any questions, please feel free to reach out to support@branch.io.

Sincerely,

The Branch Team

____________________________________________________

MORE DETAILS:

What are the two different pieces of tech here? Which one is deprecated, and which one is newer?
The install_referrer intent broadcast (docs) is the older technology. It is being replaced by the Play Install Referrer API (docs). On March 1, 2020, the former will stop operating entirely.

For most intents and purposes, these two technologies are equivalent. The newer Play Install Referrer API is more reliable (according to Google), and it contains some additional metadata about when users found and downloaded your app.

How can I tell whether my apps are impacted?
If you use the Branch Android SDK and have not linked the Play Install Referrer Library via Gradle dependency, then you will want to take one of the actions listed above.

If you use the TUNE Android SDK, you are already leveraging both the Play Install Referrer API (new) and install_referrer intent broadcast (deprecated). Most of the time, this should not be an issue. However, we still recommend updating your SDK.

If my app is impacted, what happens if I don’t update my SDK or link the InstallReferrer library by March 1, 2020?
Without Install Referrer data, the Branch Android SDK will fall back on other matching techniques. This will result in degraded attribution accuracy.

Older TUNE Android SDK versions will continue to receive Install Referrer data via the API, but in some rare cases, one of the background SDK threads may hang for up to 60 seconds while waiting for the install_referrer intent broadcast. After March 1, 2020, this intent will always be missing.

Besides updating the Android SDK, do I need to make any changes?
We recommend ensuring the deprecated InstallListener intent filter entry (shown above) has been removed from your AndroidManifest.xml file.

When I update my SDK, will any analytics or attribution change for my app?
If you are using the TUNE Android SDK, nothing will change.

If you are using the Branch Android SDK, it depends on whether you previously linked the Play Install Referrer Library via Gradle dependency. If you had, nothing will change. If you had not linked this library, you will now see some additional metadata (namely, install_begin_ts and clicked_referrer_ts).

What if I'm using a library, such as Cordova or React Native?
We are preparing updated versions of all of our modules, and anticipate these being ready prior to March 1, 2020. Please email us at support@branch.io if you have any concerns.

Do I need to force my users to upgrade app versions?
No. There is no impact on your existing app users — only on measurement for new installs.

Can I talk to someone at Branch before making the changes?
Absolutely! We’re here to help. Please email us at support@branch.io, and we’ll go over any questions you may have.

__________

**Comment by marchbold** [comment]
I'll look into updating the SDK shortly and make sure this is handled.

**Comment by idanasher** [comment]
YOU ROCK !

**Comment by marchbold** [comment]
Okay, so to include the Install referrer library you'll need to add the Android Support Install Referrer ANE to your project.

ID: `com.distriqt.androidsupport.InstallReferrer`

Located in the following repository:

https://github.com/distriqt/ANE-AndroidSupport/tree/master/lib

Adding this ANE should add the required library to your application, no changes should be required to the Branch ANE for this to be picked up.

**Comment by idanasher** [comment]
Thank again Michael.

On the wiki of the branch ane,
(here: https://github.com/distriqt/ANE-BranchIO/wiki/i.Add-the-Extension)
you have already instructed to include the .androidsupport.InstallReferrer ane, and so I did.

So just to be sure, I dont need to do anything in order to support this change ?

**Comment by marchbold** [comment]
That's all that they have directed you to do above so unless there is something else they have said?

**Comment by idanasher** [comment]
Heloow Again Michael

I have just receieved this email from branch support regarding this issue.

> Dear Customer,
> At the beginning of this month, we sent you an email with the subject “Please confirm your Play Store Referrer configuration”. We want to make a correction to this email.
> 
> Correction: if you chose to update to the newest Android SDK, then please be sure to delete the entry from AndroidManifest.xml related to the install_referrer intent broadcast. Failure to do so will result in warnings in your development console and crashes on new installs via the Play Store. Previously we referred to this step as recommended; however, it is required if you upgrade to the latest versions of the SDK (Branch Android: v4.3.2; TUNE Android: v6.1.2).
> Best,
> The Branch Team

So, if I understand correctly, I have to remove this from my  AndroidManifest.xml  :
	<receiver android:name="io.branch.referral.InstallListener" android:exported="true">
        <intent-filter>
            <action android:name="com.android.vending.INSTALL_REFERRER" />
        </intent-filter>
    </receiver>

am I right ?

**Comment by marchbold** [comment]
As this didn't involve updating the Android SDK that correction wouldn't apply. 

I think you should leave that receiver in, and I'd only remove it if you start finding issues.

**Comment by idanasher** [comment]
I have removed the receiver, and checked the app. Everything was
working fine, including all branch related issues.

Do  you still recommend not to remove it now ?

And another question,
This new play installer referral api thing did not required the Android sdk
to be updated ?

Thank a lot
Edan

**Comment by marchbold** [comment]
Yes there were no updates required. 

I am not sure whether removing it will stop the referral functionality from working, but they didn't tell you to remove it unless you were updating the SDK. If you have tested it and it is working then you should be fine to remove it.
